version: "3"

services:
  web:
    image: nginx
    hostname: nginx
    ports:
    - "8080:8080"
    - "443:443"
  network_mode:
  environment:
    - NGINX_HOST=pangarabbit.com
    - NGINX_PORT=8080
  restart: always