version: "3"
services:
  webserver:
      image: nginx:alpine
      container_name: nginx
      restart: always
      tty: true
      ports:
        - "8080:8080"
        - "443:443"
      environment: 
        - NGINX_HOST=pangarabbit.com
      volumes:
#        - ./nginx/conf.d/:/etc/nginx/conf.d/
        - ./cert.pem:/etc/ssl/cert.pem
        - ./privkey.pem:/etc/ssl/privkey.pem
        - ./etc/nginx/:/etc/nginx/conf.d/

