version: "3"
services:
  webserver:
      image: nginx:alpine
      container_name: nginx
      restart: always
      tty: true
      ports:
        - "8888:8888"
        - "4443:4443"
      environment: 
        - NGINX_HOST=pangarabbit.com
      volumes:
        - ./cert.pem:/etc/ssl/cert.pem
        - ./privkey.pem:/etc/ssl/privkey.pem

